### ISSUE TITLE
How can use with NextJS

### ISSUE THREAD

**Issue by Suniron** [christianalfoni/stitches#29]
Hi,

To begin, thanks for your job !

### Problem
I have a problem when i try to use stitches css + tailwind + styled: I got always an error message in console, like bellow:

```
Warning: Prop `className` did not match. Server: "fs_5 fw_6 c_7" Client: "fs_0 fw_1 c_2"
```

Also, if i modify something in my "style file" like add this:
```
export const appContainer = css.compose(
  css.relative(),
  css.minH("screen"),
  css.text("center")
);
```
... my page do a refresh and i see styling correctly (whitout a new error message `Warning: Prop `className` did not match. ...`) and it works until I reload the page manually.

### Configuration
I use the lastest version of stitches, NextJS, Typescript,...

This is my `_app.tsx`:
```js
import Head from "next/head";
import AppLayout from "components/AppLayout";
import { css, Provider } from "styles/css";

function MyApp({ Component, pageProps }) {
  return (
    <Provider css={css}>
      <Head>
        <title>My Application Title</title>

        <link
          href="https://unpkg.com/tailwindcss/dist/base.min.css"
          rel="stylesheet"
          key="tailwindcss"
        />
      </Head>
      <AppLayout>
        <Component {...pageProps} />
      </AppLayout>
    </Provider>
  );
}

export default MyApp;
```

I don't use `_docuemnt.tsx` for now.

I think that i have to put this line in a place, but where :
```const styles = css.getStyles(); // The styles to be passed with the resulting HTML```

Note: i'm a "beginner", in dev and in english ^_^

Thanks by advance :-)

**Comment by Suniron** [comment]
Hmm i solved this by applying the exemple which is in Next.JS Doc (good job !): https://github.com/zeit/next.js/blob/canary/examples/with-stitches/pages/css.js

With Typescript and Tailwind, serverCss type in `_App.tsx` must be:
```serverCss: TUtilityFirstCss<typeof config>```

It's work :-)

I think that a documentation for Tailwind + styled intégration should be interesting for begginers like me.

**Comment by Suniron** [comment]
I copied the `_document.js` in my `pages` folder: it work in dev mode but if i build and start, the browser is stucked on a white page and many errors are incremented in console.

Theese errors say:
![image](https://user-images.githubusercontent.com/36677774/80973325-82559a80-8e1f-11ea-89d3-875dfb4266ff.png)

While waiting to find a solution, I remove the `_document.tsx` file

**Comment by Suniron** [comment]
I found a solution to work propely with `_document.tsx` !

I have to remove comment inside the content of `<style>` tag like this:
![image](https://user-images.githubusercontent.com/36677774/81397428-9521e500-9127-11ea-8e21-3aa07b76e64e.png)

I do this because i see a comment like `/*STITCHES*/` inside, which is not valid inside the style tag.

Since this fix, i see correctly style inside browser sources ! :-)

**Comment by christianalfoni** [comment]
@Suniron Hi there and sorry for my late reply. Been moving to a new apartment this week and very little time for open source :) 

Your fix only seems to fix the problem. Having `/* comment */` in a style tag is valid and it is used by stitches to handle rehydration of styles. What you are experiencing seems to be domain related.

Do you have the project available somewhere? Does this happen locally as well? Are you running on localhost or some other domain?

**Comment by Suniron** [comment]
Hi!

No worry for waiting :-).

I've been upgraded Stitches from 2.0.5 to 2.0.6 and the problem with comment seem to be fixed, good job !

Also, TCss work proprely now, thanks !

I have 2 lasts problems:

1) With my custom config (tokens and screens here): if i do `css.tablet.bg("black") ` in a styled component, i got this error message: "@Stiches/css - The property "tablet" is not available". (I send you a mail about this)

2) I'm not a pro of Tailwind framework but when i do `css.flex("col")`, the styled component is just `dispaly: flex;` but not `flex-direction: column;`. I have to put  `style={{ flexDirection: "column" }` when i use this component to fix this.


For finish... Enjoy your new home !! 😍

**Comment by Suniron** [comment]
I just maked a template on github with the config:
https://github.com/Suniron/NextJS-stitches-overmind-typescript-boilerplate

**Comment by christianalfoni** [comment]
Hi @Suniron , just wanted to check up on you 😄 

The 2. issue is fixed in next release, did you figure out 1.?

**Comment by Suniron** [comment]
Hi !

Yes i have received help on Discord for this 2 issues ! 

I've fixed the issue 1 by adding this in the config :+1: 
```
hotReloadingCache.clear();
```

**Comment by peduarte** [comment]
Im using it with Next and it all seems good. You still having issues? 

There's been some significant updates over the last few weeks so be aware for breaking changes.

**Comment by Suniron** [comment]
Do you use tailwind + styled also ? 

Because without theese, NextJS work fine. With Tailwind + styled i got an error message about `prototype is not available`. 

I work on it on **Cerebral** Discord

**Comment by peduarte** [comment]
hmm interesting. Im only using the `styled` package atm so maybe that's why I don't have this issue

**Comment by Suniron** [comment]
Hmm i can close this issue because the principal problem wich i mean was solved recently.

But, my Tailwind problem is described here: https://github.com/christianalfoni/stitches/issues/32 i have to make an exemple on codesandbox
