### ISSUE TITLE
Tailwind `flex(1)` uses `flex-direction` property

### ISSUE THREAD

**Issue by kingdaro** [christianalfoni/stitches#49]
With tailwind, `css.flex(1)` doesn't correctly apply the css property `flex: 1, 1, 0%`, it tries to apply `flex-direction` instead. [Here's a sandbox repro.](https://codesandbox.io/s/stitches-tailwind-sandbox-3fzuf?file=/src/index.ts)

I fixed it locally by changing the flex util to this:
```js
export var flex = createUtility(function (css, value, pseudo) {
    return value === "1, 1, 0%"
        ? css.compose(css.flexGrow(1, pseudo), css.flexShrink(1, pseudo), css.flexBasis('0%', pseudo))
        : css.flexDirection(value, pseudo);
}, {
    theme: "flex",
    emptyValue: function (css, pseudo) { return css.display("flex", pseudo); },
    values: {
        col: "column",
        "col-reverse": "column-reverse",
    },
});
```
...but I feel like there's probably a more proper way to go about it. A separate `flex1` helper might be a good idea, too

**Comment by peduarte** [comment]
This should've been fixed now, can you validate and close once confirmed? Thanks!

**Comment by kingdaro** [comment]
I updated the [sandbox](https://codesandbox.io/s/stitches-tailwind-sandbox-3fzuf?file=/src/index.ts) to the latest published versions of `@stitches/css` and `@stitches/tailwind`, and the issue still occurs

**Comment by peduarte** [comment]
@kingdaro and now?
